### ISSUE TITLE
Queue cleaning is unused

### ISSUE THREAD

**Issue by yankovs** [danielplohmann/mcrit#38]
Regarding:
https://github.com/danielplohmann/mcrit/blob/160c4612a2d2a58fede23a84fe59b199696dcbf5/mcrit/libs/mongoqueue.py#L285

Is this intentional? since `cache_time` is `10 ** 9`, it will actually cache for over 30 years and this `clean` function is essentially a dead path of code.

**Comment by danielplohmann** [comment]
Let's say the use of the queue is still beta (also visible in how jobs are shown in the tab in mcritweb) and we just decided on some value that we considered "long enough for data to remain". ;)

Right now, the queue documents are the only tangible reference for all jobs, meaning that if they got cleaned up, you weren't able to easily retrieve the matching results etc. 
It would probably make sense to store those matching results (or rather references to them, as the results themselves need to remain in gridfs for size reasons) with some additional meta data in their own collection after completion as all other queue objects / results have less value after completion (updating minhashes, adding binaries, renaming/deleting samples/families, ...).
