### ISSUE TITLE
Improve performance of job page

### ISSUE THREAD

**Issue by danielplohmann** [danielplohmann/mcrit#46]
The jobs page is currently very slow when having a large queue.
One reason for this is certainly that the queue is barely using any indices on fields but also that rendering the page carries out multiple full collection scans and data retrievals as [JobResource](https://github.com/danielplohmann/mcrit/blob/main/mcrit/server/JobResource.py) is doing the start/limit and filtering instead of having the database/MongoDB do this efficiently.

In order to improve performance for this, 
* the jobs page could be split up into multiple pages per Job type (Matching, Query, Blocks, Other)
* start/limits could be performed efficiently on the DB
* cleanup functionality for the queue should be exposed to the front-end (related to #38)

**Comment by danielplohmann** [comment]
commit 435dc22 should now provide the foundation to address several of these things in the frontend.

**Comment by danielplohmann** [comment]
As a first step, this has now been integrated in `v1.2.8`, and should provide much better performance. Looks like this:
![image](https://github.com/danielplohmann/mcrit/assets/9798598/7adee3b2-4b21-43b5-a8de-b23c162c9599)

The next step would be an extension with filtering for lists of `sample_id` and `family_id` (for rapid selection in the sample table) and exposing queue deletion functionality in the frontend.
@yankovs feel free to test if the job page is more responsive now for your collection.

**Comment by yankovs** [comment]
Wow, this looks amazing! Great job :)

Our huge MCRIT instance is unfortunately down in favor of a slimmer one with much less samples. But i'll still test it out, maybe even on a local instance with lots of samples.
