### ISSUE TITLE
Reassign unstarted jobs on crashed worker

### ISSUE THREAD

**Issue by yankovs** [danielplohmann/mcrit#49]
Hey! 😄
Regarding: 

https://github.com/danielplohmann/mcrit/blob/435dc221de1af493481ec5ca08aa8bba6b3ab1a2/mcrit/libs/mongoqueue.py#L381-L386

I'm not 100% sure how dispatching of jobs in MCRIT works so this question might be irrelevant. Is it possible for jobs to be assigned to a worker while it is still processing some other job? Meaning they are locked, but `started_at == None`. If so, then it might also make sense to release those jobs so they can be either:
* taken by other workers to be processed
* taken by the same worker in case some worker recovery/restart mechanism is implemented

**Comment by danielplohmann** [comment]
Hi!
Just had a look, `locked_by` and `started_at` are set in the same DB update, so it should not be possible to pre-assign jobs to certain workers.
With the latest change, a worker should also not have more than unfinished/failed job marked `locked_by` as the context manager should release it upon crash. 
Are you seeing such documents in your `db.queue` collection?

**Comment by yankovs** [comment]
No, we do not see any such documents. I just wanted to make sure I didn't miss anything :)
Thanks! Closing this issue.
