### ISSUE TITLE
Question: PicHash and MinHash recalculation results

### ISSUE THREAD

**Issue by yankovs** [danielplohmann/mcrit#60]
Hey!

I'd ask this in private, but I assume this question applies to more people so it can help others.
We recently did the recalculation actions needed for the new upgraded SMDA, and these are the results:

![image](https://github.com/danielplohmann/mcrit/assets/49753115/7ff4bce3-922e-40e4-9aad-c8e88576a5a8)
![image (1)](https://github.com/danielplohmann/mcrit/assets/49753115/60e9b051-5c10-45bc-822b-ff8c4e7360a8)

In particular, we noticed only ~1/2 of updatable functions were updated in PIcHash recalculation, and similarly for PicBlockHashes only a small fraction was actually updated.

Is this behavior normal? How can we assure that those were not updated because of an error?

Thank you :)

**Comment by danielplohmann** [comment]
Hey!

Oh sorry, i guess that was suboptimal wording on my part. :D

No, it's definitely fine like this.
The changes to pichash calculation only affect a subset of instructions. So when they don't appear in functions/blocks, the pichash will actually remain the same.

Ratio shown here is similar to what I observed on my instance so I'd say that it's most likely as expected.

In any case, all values were now calculated consistently, which is the main goal of this operation anyway. 

Am 28. Januar 2024 08:27:43 MEZ schrieb Sharon Yankovich ***@***.***>:
>Hey!
>
>I'd ask this in private, but I assume this question applies to more people so it can help others.
>We recently did the recalculation actions needed for the new upgraded SMDA, and these are the results:
>
>![image](https://github.com/danielplohmann/mcrit/assets/49753115/7ff4bce3-922e-40e4-9aad-c8e88576a5a8)
>![image (1)](https://github.com/danielplohmann/mcrit/assets/49753115/60e9b051-5c10-45bc-822b-ff8c4e7360a8)
>
>In particular, we noticed only ~1/2 of updatable functions were updated in PIcHash recalculation, and similarly for PicBlockHashes only a small fraction was actually updated.
>
>Is this behavior normal? How can we assure that those were not updated because of an error?
>
>Thank you :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/danielplohmann/mcrit/issues/60
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
